// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMx8hIIBR2tA43OZhpNm5cKu1EDOnn2sY',
    appId: '1:1069523492509:web:69b5a7e91b5b52c19cbe74',
    messagingSenderId: '1069523492509',
    projectId: 'almardanov',
    authDomain: 'almardanov.firebaseapp.com',
    storageBucket: 'almardanov.appspot.com',
    measurementId: 'G-958WV8S1FP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGo6MzakR-WYaTPv6ZHLOiRhruK-FaFuU',
    appId: '1:1069523492509:android:0b523e8d2601c36f9cbe74',
    messagingSenderId: '1069523492509',
    projectId: 'almardanov',
    storageBucket: 'almardanov.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCueIVJCURL7YPjdUZmCBqhstDGKMIp87w',
    appId: '1:1069523492509:ios:e7f55f458cd663889cbe74',
    messagingSenderId: '1069523492509',
    projectId: 'almardanov',
    storageBucket: 'almardanov.appspot.com',
    iosClientId: '1069523492509-akrhi9u251j05f57bhrr4s01jpdvp1lo.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizapp',
  );
}
