// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcfz5_1-7INxchuUGlVj92bVIJfH8n578',
    appId: '1:598114544247:web:0c3947ff8aa61f8289f472',
    messagingSenderId: '598114544247',
    projectId: 'quiz-app-7d828',
    authDomain: 'quiz-app-7d828.firebaseapp.com',
    storageBucket: 'quiz-app-7d828.appspot.com',
    measurementId: 'G-JP7BEX2EVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKkXuq6q1Zi-Y7tFjKXe_2mIH1B-MDo6U',
    appId: '1:598114544247:android:a54b192fb635a3d089f472',
    messagingSenderId: '598114544247',
    projectId: 'quiz-app-7d828',
    storageBucket: 'quiz-app-7d828.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBDfwBSE-LCSfkUnfEpp71FIj1v9krRjc',
    appId: '1:598114544247:ios:0c7164ab48a392d489f472',
    messagingSenderId: '598114544247',
    projectId: 'quiz-app-7d828',
    storageBucket: 'quiz-app-7d828.appspot.com',
    androidClientId: '598114544247-onql5qig8nmc3oqcjmfhg3qav67tiegk.apps.googleusercontent.com',
    iosClientId: '598114544247-grd0ha7qfjdedcuf4hqqm7angvrjbegc.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBDfwBSE-LCSfkUnfEpp71FIj1v9krRjc',
    appId: '1:598114544247:ios:0c7164ab48a392d489f472',
    messagingSenderId: '598114544247',
    projectId: 'quiz-app-7d828',
    storageBucket: 'quiz-app-7d828.appspot.com',
    androidClientId: '598114544247-onql5qig8nmc3oqcjmfhg3qav67tiegk.apps.googleusercontent.com',
    iosClientId: '598114544247-grd0ha7qfjdedcuf4hqqm7angvrjbegc.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizapp',
  );
}
